// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createMockSupabaseClient } from './mockClient';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Демо-режим включается, если реальные ключи Supabase не заданы (или это плейсхолдер).
// В этом режиме используется мок-клиент с демо-данными — приложение полностью
// работает без бэкенда. Как только добавите настоящие ключи в .env.local,
// автоматически подключится реальный Supabase.
const isPlaceholder = (v?: string) =>
  !v || v.includes('your-project') || v.includes('placeholder') || v.trim() === '';

export const isDemoMode =
  isPlaceholder(SUPABASE_URL) || isPlaceholder(SUPABASE_PUBLISHABLE_KEY);

let supabaseClient: any;

if (isDemoMode) {
  console.info(
    '%c[SeoMarket] Демо-режим: показаны демонстрационные данные. ' +
      'Добавьте VITE_SUPABASE_URL и VITE_SUPABASE_PUBLISHABLE_KEY в .env.local для подключения реального бэкенда.',
    'color:#f59e0b;font-weight:bold'
  );
  supabaseClient = createMockSupabaseClient();
} else {
  supabaseClient = createClient<Database>(
    SUPABASE_URL as string,
    SUPABASE_PUBLISHABLE_KEY as string,
    {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    }
  );
}

export const supabase = supabaseClient;
