
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjrcutrjltukskwicjnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqcmN1dHJqbHR1a3Nrd2ljam54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NjcxMjcsImV4cCI6MjA2MDM0MzEyN30.hrJtobLOHRl4_pD_w8805EnZhJraufDgXtm9JdYOVIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
